name: Framework
main: com.daytonjwatson.framework.FrameworkPlugin
author: DaytonJWatson
description: Framework plugin for MC servers
version: 0.0.1
api-version: '1.21'
commands:
  help:
    description: Show help
  list:
    description: List players
  motd:
    description: Show message of the day
  rules:
    description: Show rules
  spawn:
    description: Teleport to spawn
  setspawn:
    description: Set spawn
    permission: framework.setspawn
  warp:
    description: Teleport to warp
  setwarp:
    description: Create a warp
    permission: framework.setwarp
  warps:
    description: List warps
  home:
    description: Teleport to home
  sethome:
    description: Set a home
  delhome:
    description: Delete a home
  homes:
    description: List homes
  tpa:
    description: Request teleport
  tpahere:
    description: Request a player to teleport to you
  tpaccept:
    description: Accept teleport request
  tpdeny:
    description: Deny teleport request
  back:
    description: Teleport back
  msg:
    description: Send private message
  reply:
    description: Reply to private message
    aliases: r
  ignore:
    description: Ignore player
  nickname:
    description: Set nickname
  realname:
    description: Lookup real name
  rtp:
    description: Random teleport
  trash:
    description: Open trash inventory
  enderchest:
    description: Open ender chest
    aliases: ec
  workbench:
    description: Open workbench
    aliases: wb
  stats:
    description: View stats
  playtime:
    description: View playtime
  pillar:
    description: Toggle automatic pillaring when placing blocks
    permission: framework.pillar
  ban:
    description: Ban player
    permission: framework.ban
  playersettings:
    description: Open player-specific settings
    permission: framework.playersettings
  tempban:
    description: Temporarily ban player
    permission: framework.tempban
  unban:
    description: Unban player
    permission: framework.unban
  mute:
    description: Mute player
    permission: framework.mute
  tempmute:
    description: Temp mute player
    permission: framework.tempmute
  unmute:
    description: Unmute player
    permission: framework.unmute
  kick:
    description: Kick player
    permission: framework.kick
  warn:
    description: Warn player
    permission: framework.warn
  warnings:
    description: View warnings
    permission: framework.warnings
  time:
    description: Set time
  weather:
    description: Set weather
  gamemode:
    description: Set gamemode
    aliases: gm
    permission: framework.gamemode
  tp:
    description: Teleport to player
    permission: framework.tp
  tphere:
    description: Teleport a player to you
    permission: framework.tphere
  tpall:
    description: Teleport all to you
    permission: framework.tpall
  fly:
    description: Toggle flight
    permission: framework.fly
  god:
    description: Toggle god mode
    permission: framework.god
  heal:
    description: Heal
    permission: framework.heal
  feed:
    description: Feed
    permission: framework.feed
  vanish:
    description: Toggle vanish
    permission: framework.vanish
    aliases: v
  invsee:
    description: View inventory
    permission: framework.invsee
  endersee:
    description: View ender chest
    permission: framework.endersee
  clear:
    description: Clear inventory
    permission: framework.clear
  give:
    description: Give items
    permission: framework.give
  enchant:
    description: Enchant item
    permission: framework.enchant
  broadcast:
    description: Broadcast message
    permission: framework.broadcast
  autocrop:
    description: Open the auto crop settings menu
    permission: framework.autocrop
  nuker:
    description: Break nearby blocks using the held tool
    permission: framework.nuker
