name: Framework
main: com.framework.FrameworkPlugin
version: 1.0.0
author: OpenAI
description: Basic commands framework with API for future plugins.
api-version: 1.19
commands:
  help:
    description: Framework help command
    usage: /help [command]
    permission: framework.help
  list:
    description: List online players
    usage: /list
    permission: framework.list
  motd:
    description: Show message of the day
    usage: /motd
    permission: framework.motd
  rules:
    description: Show server rules
    usage: /rules
    permission: framework.rules
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: framework.spawn
  setspawn:
    description: Set world spawn
    usage: /setspawn
    permission: framework.setspawn
  warp:
    description: Teleport to a warp
    usage: /warp <name>
    permission: framework.warp
  setwarp:
    description: Create a warp
    usage: /setwarp <name>
    permission: framework.setwarp
  warps:
    description: List warps
    usage: /warps
    permission: framework.warps
  home:
    description: Teleport home
    usage: /home [name]
    permission: framework.home
  sethome:
    description: Set a home
    usage: /sethome [name]
    permission: framework.sethome
  delhome:
    description: Delete a home
    usage: /delhome <name>
    permission: framework.delhome
  homes:
    description: List homes
    usage: /homes
    permission: framework.homes
  tpa:
    description: Request teleport
    usage: /tpa <player>
    permission: framework.tpa
  tpaccept:
    description: Accept teleport
    usage: /tpaccept
    permission: framework.tpa
  tpdeny:
    description: Deny teleport
    usage: /tpdeny
    permission: framework.tpa
  back:
    description: Return to previous location
    usage: /back
    permission: framework.back
  suicide:
    description: End yourself
    usage: /suicide
    permission: framework.suicide
  afk:
    description: Toggle AFK
    usage: /afk
    permission: framework.afk
  msg:
    description: Send private message
    usage: /msg <player> <message>
    permission: framework.msg
  reply:
    description: Reply to last message
    usage: /reply <message>
    permission: framework.msg
  ignore:
    description: Ignore a player
    usage: /ignore <player>
    permission: framework.ignore
  seen:
    description: Check last seen
    usage: /seen <player>
    permission: framework.seen
  nickname:
    description: Set nickname
    usage: /nickname <name>
    permission: framework.nickname
  realname:
    description: Get real name
    usage: /realname <player>
    permission: framework.nickname
  rtp:
    description: Random teleport
    usage: /rtp
    permission: framework.rtp
  trash:
    description: Open trash inventory
    usage: /trash
    permission: framework.trash
  enderchest:
    description: Open ender chest
    usage: /enderchest [player]
    permission: framework.enderchest
  workbench:
    description: Open workbench
    usage: /workbench
    permission: framework.workbench
  stats:
    description: Show stats
    usage: /stats
    permission: framework.stats
  playtime:
    description: Show playtime
    usage: /playtime
    permission: framework.playtime
  ban:
    description: Ban player
    usage: /ban <player> <reason>
    permission: framework.ban
  tempban:
    description: Temp ban player
    usage: /tempban <player> <time> <reason>
    permission: framework.ban
  unban:
    description: Unban player
    usage: /unban <player>
    permission: framework.ban
  mute:
    description: Mute player
    usage: /mute <player>
    permission: framework.mute
  tempmute:
    description: Temporarily mute
    usage: /tempmute <player> <time>
    permission: framework.mute
  kick:
    description: Kick player
    usage: /kick <player> <reason>
    permission: framework.kick
  warn:
    description: Warn player
    usage: /warn <player> <reason>
    permission: framework.warn
  warnings:
    description: View warnings
    usage: /warnings <player>
    permission: framework.warn
  time:
    description: Set time
    usage: /time <value>
    permission: framework.time
  weather:
    description: Set weather
    usage: /weather <clear|rain|thunder>
    permission: framework.weather
  gamemode:
    description: Set gamemode
    usage: /gamemode <mode> [player]
    permission: framework.gamemode
  tp:
    description: Teleport to player
    usage: /tp <player>
    permission: framework.tp
  tpall:
    description: Teleport all players
    usage: /tpall
    permission: framework.tp
  fly:
    description: Toggle flight
    usage: /fly
    permission: framework.fly
  god:
    description: Toggle god mode
    usage: /god
    permission: framework.god
  heal:
    description: Heal yourself or others
    usage: /heal [player]
    permission: framework.heal
  feed:
    description: Feed yourself or others
    usage: /feed [player]
    permission: framework.feed
  vanish:
    description: Toggle vanish
    usage: /vanish
    permission: framework.vanish
  invsee:
    description: View inventory
    usage: /invsee <player>
    permission: framework.invsee
  endersee:
    description: View ender chest
    usage: /endersee <player>
    permission: framework.endersee
  clear:
    description: Clear inventory
    usage: /clear [player]
    permission: framework.clear
  give:
    description: Give item
    usage: /give <player> <item> [amount]
    permission: framework.give
  enchant:
    description: Enchant held item
    usage: /enchant <name> [level]
    permission: framework.enchant
  broadcast:
    description: Broadcast message
    usage: /broadcast <message>
    permission: framework.broadcast
