name: Framework
main: com.daytonjwatson.framework.FrameworkPlugin
author: DaytonJWatson
description: Framework plugin for MC servers
version: 0.0.1
api-version: '1.21'
commands:
  help:
    description: Show help
  list:
    description: List players
  motd:
    description: Show message of the day
  rules:
    description: Show rules
  spawn:
    description: Teleport to spawn
  setspawn:
    description: Set spawn
  warp:
    description: Teleport to warp
  setwarp:
    description: Create a warp
  warps:
    description: List warps
  home:
    description: Teleport to home
  sethome:
    description: Set a home
  delhome:
    description: Delete a home
  homes:
    description: List homes
  tpa:
    description: Request teleport
  tpahere:
    description: Request a player to teleport to you
  tpaccept:
    description: Accept teleport request
  tpdeny:
    description: Deny teleport request
  back:
    description: Teleport back
  msg:
    description: Send private message
  reply:
    description: Reply to private message
    aliases: r
  ignore:
    description: Ignore player
  nickname:
    description: Set nickname
  realname:
    description: Lookup real name
  rtp:
    description: Random teleport
  trash:
    description: Open trash inventory
  enderchest:
    description: Open ender chest
    aliases: ec
  workbench:
    description: Open workbench
    aliases: wb
  stats:
    description: View stats
  playtime:
    description: View playtime
  ban:
    description: Ban player
  tempban:
    description: Temporarily ban player
  unban:
    description: Unban player
  mute:
    description: Mute player
  tempmute:
    description: Temp mute player
  unmute:
    description: Unmute player
  kick:
    description: Kick player
  warn:
    description: Warn player
  warnings:
    description: View warnings
  time:
    description: Set time
  weather:
    description: Set weather
  gamemode:
    description: Set gamemode
    aliases: gm
  tp:
    description: Teleport to player
  tphere:
    description: Teleport a player to you
  tpall:
    description: Teleport all to you
  fly:
    description: Toggle flight
  god:
    description: Toggle god mode
  heal:
    description: Heal
  feed:
    description: Feed
  vanish:
    description: Toggle vanish
  invsee:
    description: View inventory
  endersee:
    description: View ender chest
  clear:
    description: Clear inventory
  give:
    description: Give items
  enchant:
    description: Enchant item
  broadcast:
    description: Broadcast message
